"""Homepage FAQ — 20+ items for SEO and AdSense depth."""

HOME_FAQS = [
    {"q": "What is FileShrinkr?", "a": "FileShrinkr is a free online tool to compress images, export PDFs, and edit photos in your browser. No account is required."},
    {"q": "Which image formats can I upload?", "a": "You can upload JPG, PNG, WEBP, HEIC (iPhone photos), and SVG files. Output formats include JPG, WEBP, AVIF, PNG, and PDF."},
    {"q": "Is FileShrinkr free?", "a": "Yes. Compression and editing are free with no signup or subscription."},
    {"q": "How does compression work?", "a": "Choose Browser mode to compress JPG, WEBP, AVIF, or PNG locally in your browser, or Server mode for PDF export, HEIC conversion, EXIF removal, and MozJPEG JPG optimization on our server."},
    {"q": "Are my files stored permanently?", "a": "In Browser mode, raster compression stays on your device. In Server mode, uploads are used in a temporary batch folder and are not intended to be retained after processing."},
    {"q": "Can I compress multiple images at once?", "a": "Yes. Upload several files and download a ZIP archive containing all compressed results."},
    {"q": "How do I merge images into one PDF?", "a": "Select PDF as the output format and enable Merge all images into one PDF before compressing."},
    {"q": "What is the lossless PDF option?", "a": "When compress images in PDF is unchecked, we embed originals with img2pdf to avoid re-encoding quality loss."},
    {"q": "Does the image editor run locally?", "a": "Yes. Crop, resize, rotate, and flip use HTML5 Canvas in your browser. Compression can run in the browser (private mode) or on our server."},
    {"q": "What quality setting should I use?", "a": "Start at 75 for a balance of size and clarity. Email attachments often work at 70; web heroes may use 80–85."},
    {"q": "Can I use FileShrinkr on mobile?", "a": "The site works on modern mobile browsers. Large batches may be slower on limited connections."},
    {"q": "Why is my download delayed?", "a": "We add a short filesystem sync delay so browsers reliably start downloads, especially in Chrome."},
    {"q": "Does FileShrinkr remove EXIF metadata?", "a": "Enable Remove EXIF in Server mode to strip camera and GPS metadata from JPG, WEBP, and AVIF outputs. Browser mode re-encodes images but does not offer full EXIF stripping."},
    {"q": "Can I upload iPhone HEIC photos?", "a": "Yes. Use Server mode or let Browser mode fall back to the server when your browser cannot decode HEIC. Output can be JPG, WEBP, AVIF, or PDF."},
    {"q": "What is AVIF and when should I use it?", "a": "AVIF is a modern image format that often produces smaller files than WEBP at similar quality. Use it for websites when visitors use current browsers. Choose JPG for maximum email compatibility."},
    {"q": "Does browser mode upload my files?", "a": "No. In Browser (private) mode, JPG, WEBP, AVIF, and PNG compression runs locally with the Canvas API. PDF, lossless PDF, EXIF removal, HEIC fallback, and MozJPEG JPG use the server only when needed."},
    {"q": "Can I resize for Instagram?", "a": "Use the Instagram 1080×1080 resize preset on the compressor, or enter custom width and height for a center cover crop. The editor tab also supports free-form crop and resize before you compress."},
    {"q": "Can I resize a photo for a government exam or job application form?", "a": "Yes. Use the Image Editor to crop and resize, then set a target file size (20 KB, 100 KB, or 500 KB) or enter custom width and height on the compressor. Many SSC, UPSC, railway, and state recruitment portals require small JPG uploads — see our guide on resizing photos for government exam forms for a step-by-step checklist."},
    {"q": "How do I compress a photo to 20 KB for an online form?", "a": "Select the 20 KB target size preset, choose JPG output, and compress. If the portal also specifies pixel dimensions, resize in the editor first (for example 200×230 or as listed in the form instructions), then compress with the target KB option."},
    {"q": "Can I compress to a specific file size?", "a": "Yes. Choose a target size of 20 KB, 100 KB, or 500 KB for JPG, WEBP, or AVIF. FileShrinkr picks the highest quality that stays under your limit. If the target cannot be reached, you get the smallest result with a warning."},
    {"q": "Can I export lossless PNG?", "a": "Yes. Select PNG as the output format and keep Lossless PNG enabled to preserve transparency. PNG is ideal for graphics, logos, and screenshots."},
    {"q": "Is there a before and after preview?", "a": "After compression, a slider preview compares your original and compressed image. For batches, the preview shows the first file."},
    {"q": "Can I compress an image after editing it?", "a": "Yes. In the Image Editor tab, click Compress This Image to send your edited canvas to the compressor without re-uploading."},
    {"q": "Is WEBP better than JPG?", "a": "WEBP often produces smaller files at similar quality. JPG remains more compatible with older email clients."},
    {"q": "Do you sell my data?", "a": "No. We do not sell personal information. See our Privacy Policy for analytics and advertising disclosures."},
    {"q": "How do I contact support?", "a": "Use the Contact page or email us. We aim to respond within 24–48 hours."},
    {"q": "Can I use compressed images commercially?", "a": "You retain rights to your images. You are responsible for complying with licenses and applicable laws."},
    {"q": "What if compression fails?", "a": "Try a different format, lower file size, or ensure the file is a valid image. Corrupt files may be rejected."},
    {"q": "Does FileShrinkr work offline?", "a": "The editor and Browser compression mode can work on loaded images without uploading them. Server mode and PDF features require an internet connection."},
    {"q": "Who operates FileShrinkr?", "a": "FileShrinkr is published by DSnM Solutions. Learn more on our About page."},
]
